name: Publish

on:
  push:
    tags: ["*"]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm

      - name: Check version
        run: |
          VERSION="$(cat package.json | jq -r '.version')"
          if [ "$VERSION" != "${{ github.ref_name }}" ]; then
            echo -e "Version mismatch.\npackage.json: $VERSION\ntag: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Build
        run: |
          pnpm build

      - name: Publish
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm

      - name: Check version
        run: |
          VERSION="$(cat jsr.json | jq -r '.version')"
          if [ "$VERSION" != "${{ github.ref_name }}" ]; then
            echo -e "Version mismatch.\njsr.json: $VERSION\ntag: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Build
        run: |
          pnpm build

      - name: Publish
        run: |
          pnpm jsr publish
